export const dates = [
{id:1,
image: require("./../assets/beach.jpg"),
destination: "Shkemb i Kavajes",
location:"Albania",
grade: "Cultur Relax",
price: "800€",
description: "The romance,Shkembi i Kavajes is one of the best travel destinations in the World. This place is know dor its luxurious stays and adventurous activities?",
review_text: "Very good",
reviews: "3.545",
rating: "8.5"
},
{id:2,
     image: require("./../assets/SyriKalter.jpeg"),
     destination: "Syri i Kalter",
     location:"Albania",
     grade: "Cultur Relax",
     price: "400€",
     description: "The romance,Syri i Kalter is one of the best travel destinations in the World. This place is know dor its luxurious stays and adventurous activities?",
     review_text: "Very good",
     reviews: "3.545",
     rating: "8.5"
     },
     {id:3,
          image: require("./../assets/KD.jpg"),
          destination: "Kodra e Diellit",
          location:"Mazedonia",
          grade: "Cultur Relax",
          price: "800€",
          description: "The romance,Shkembi i Kavajes is one of the best travel destinations in the World. This place is know dor its luxurious stays and adventurous activities?",
          review_text: "Very good",
          reviews: "3.545",
          rating: "8.5"
          },
          {id:4,
               image: require("./../assets/saranda.jpg"),
               destination: "Saranda",
               location:"Albania",
               grade: "Cultur Relaxa",
               price: "500€",
               description: "The romance,Shkembi i Kavajes is one of the best travel destinations in the World. This place is know dor its luxurious stays and adventurous activities?",
               review_text: "Very good",
               reviews: "3.545",
               rating: "8.5"
               },
               {id:5,
                    image: require("./../assets/ks.jpg"),
                    destination: "PRIZREN",
                    location:"Kosov Prizren",
                    grade: "Cultur Relax",
                    price: "800€",
                    description: "The romance,Shkembi i Kavajes is one of the best travel destinations in the World. This place is know dor its luxurious stays and adventurous activities?",
                    review_text: "Very good",
                    reviews: "3.545",
                    rating: "8.5"
                    },
]
